// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrtnndwxvntqxrspdsfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxydG5uZHd4dm50cXhyc3Bkc2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMjIyODIsImV4cCI6MjA5MDU5ODI4Mn0.pN_rIN0tj66CIpJQeMGinLUt3gGLRmtbj6GDvlJjj94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});